### ISSUE TITLE
OsateResourceUtil bug?

### ISSUE THREAD

**Issue by lwrage** [lwrage/osate2-core#43]
<a href="https://github.com/mnam"><img src="https://avatars0.githubusercontent.com/u/1434565?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mnam](https://github.com/mnam)**
_Tue Feb 21 18:38:48 2012_
_Originally opened as https://github.com/osate/osate2-core/issues/42_

----

Quick question in the OSATE code.

Is the OsateResourceUtil suppose to be fully working?

When I use a defaultTraversalAllDeclarativeModels() on one of my switches

it eventually calls the visitWorkspaceDeclarativeModels() in AbstractSimpleTraversal and the problem is that

When it does

final EList<Resource> resources = OsateResourceUtil.getResourceSet().getResources();

it gets a zero list always.

Am I suppose to do something in the OSATE environment to load up OsateResourceUtil?

Only code that uses this is the architecture ModelStatisticsAnalysis plug in and you can see that

it also shows 0 for component type declarations, 0 component implementation declarations, and so on

for any model because of this problem.

Thanks.
Sincerely,
Min Young Nam

**Comment by lwrage** [comment]
<a href="https://github.com/philip-alldredge"><img src="https://avatars2.githubusercontent.com/u/1376364?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [philip-alldredge](https://github.com/philip-alldredge)**
_Wed Feb 22 21:10:34 2012_

----

Min Young,
I think I have encountered a similar issue. This seems like a bug to me.

In my plugin I am currently using a workaround. Try calling Aadl2Activator.getInstance();  before using defaultTraversalAllDeclarativeModels(). This seems to perform some initialization that isn't done under some circumstances.

**Comment by lwrage** [comment]
<a href="https://github.com/mnam"><img src="https://avatars0.githubusercontent.com/u/1434565?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mnam](https://github.com/mnam)**
_Wed Feb 22 22:08:43 2012_

----

Thanks for the comment but I'm afraid this doesn't work for me.
Tried calling Aadl2Activator.getInstance() at the start of my plug-in and in some other places but
OsateResourceUtil.getResourceSet().getResources() still gives a zero size list.

But good to know that it can work in some way. I don't think my build is wrong since even from the master snap-shot
the Analysis -> Architecture -> Model statistics plug-in shows zero for any declaritive types.

**Comment by lwrage** [comment]
<a href="https://github.com/philip-alldredge"><img src="https://avatars2.githubusercontent.com/u/1376364?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [philip-alldredge](https://github.com/philip-alldredge)**
_Wed Feb 22 22:14:18 2012_

----

My issue concerned using another method in OsateResourceUtil. I have not used getResourceSet so your initial thoughts about it not working may be correct.

**Comment by lwrage** [comment]
<a href="https://github.com/reteprelief"><img src="https://avatars1.githubusercontent.com/u/750520?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [reteprelief](https://github.com/reteprelief)**
_Fri Feb 24 03:28:09 2012_

----

Hi Min Young, Philip,

this is something I need to correct in short order.
In OSATE 1.5 all resoruces in a workspace were always loaded. Therefore, if you wanted to process all declarative models the traversal could just find all of them in the resource set. You would traverse declarative models that may be unrelated.

In Osate V2 we have the issue that XText does lazy loading of resources, thus, we cannot assume that they declarative models are all loaded.
However, we can take advantage of AADL V2 with clause  to find all the declarative packages that actually are part of a given model.

What kind of processing are you trying to do on the model? In most cases my analysis plug-ins traverse the instance model and the trversal methods should work ok for that.

**Comment by lwrage** [comment]
<a href="https://github.com/mnam"><img src="https://avatars0.githubusercontent.com/u/1434565?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mnam](https://github.com/mnam)**
_Fri Feb 24 15:40:26 2012_

----

Hi Peter,

I use the defaultTraversalAllDeclarativeModels() to go through the workspace and find all process types that are declared
and create a window with a list of available processes.
From the window, I could just drag a process to a processor to add an application to a model. Connections are created through steps in a wizard. So I need to be able to traverse through the workspace.

This lazy loading is indeed causing me other problems. I normally would like to save any model changes into the declaritive model as well and not just the instance model.
I'll usually get the ComponentClassifier of a ComponentInstance to do this and the Resource of ComponentClassifier is usually not loaded. At first I thought EcoreUtil.resolveAll() would always solve this.
But, it causes some resolving errors for some elements (I'm thinking it is not loaded and thus randomly appears)

Also I had this case. I would comment out some lines in a type definition in AADL. Even clean the work space and rebuild.
Run my tool. Do something that would update the type definition in resource. Then unparse it to aadl.
What I would see is the aadl file is the added changes that I made but also the commented lines UNCOMMENTED.
It looks like the commented model was not loaded yet even if I do a rebuild.

Is there a way of forcing the load of single resources before I update them and reparse it? I'm currently trying to figure this out.

**Comment by lwrage** [comment]
<a href="https://github.com/reteprelief"><img src="https://avatars1.githubusercontent.com/u/750520?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [reteprelief](https://github.com/reteprelief)**
_Fri Feb 24 15:43:16 2012_

----

Thanks for that feedback. 
It helps me determine how to best address these issues.

Peter

-----Original Message-----

**Comment by lwrage** [comment]
<a href="https://github.com/peterhfeiler"><img src="https://avatars2.githubusercontent.com/u/1461492?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [peterhfeiler](https://github.com/peterhfeiler)**
_Mon Feb 27 14:56:01 2012_

----

I have some methods now that work with the EMF index maintained by XText. 
They give you the set of packages or the set of classifiers in packages without loading the model.
This is useful when you want to let the user select a classifier,e.g., to be used for construction - without loading the whole world into memory.
They are Description objects that contain the name, qualified name, the EClass, and the URI to the actual object. The later is given to you as object if in memory or as proxy.
I'll write something up about that on the Wiki.

A question to you: In your scenario, where you drag the process to the processor, are you dragging an instance of a process, i.e., work with the instance model, or are you dragging a process type or implementation and as a result create a subcomponent and/or instance object?

I am using the ModelStatistics example to make sure things work better. 

I'll also look at the other issue you mentioned: changing and updating the model

**Comment by lwrage** [comment]
<a href="https://github.com/mnam"><img src="https://avatars0.githubusercontent.com/u/1434565?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mnam](https://github.com/mnam)**
_Mon Feb 27 21:58:56 2012_

----

I have both functionalities. When dragging some component that is already there, it is the instance model but I do update the type definitions, well at least try although some information is missing. When adding a new component that is not in the instance model, I would have it dragged from a table and it is initially a type or implementation. After updating the type definition, I reinstantiate the whole model to update the instance model just to be sure. Use to do a partial instantiation but just made it whole.

Great, I'll look in the ModelStatistics plugin as a samle code when it is up.

Not sure if I'm doing something wrong here but I had repeated instances where I would make change 1 and change 2 to the same resource. Both do a load and resolve before making any changes. Even checked that the property values were correctly changed for change 1 even after doing change 2.
Now I would unparse twice, after change 1 and change 2. The resulting file had only change 1 in the end 90 percent of the time. Sometimes it had change 1 and change 2. Unparsing just once did solve it but I had to write code for storing all the resources that I change so that I wont unparse the same file twice.
But why wouldn't change 2 be unparsed?

**Comment by lwrage** [comment]
<a href="https://github.com/philip-alldredge"><img src="https://avatars2.githubusercontent.com/u/1376364?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [philip-alldredge](https://github.com/philip-alldredge)**
_Tue Feb 28 15:29:46 2012_

----

I have come across an occasion where I need to get access to the declarative models without going through the instance model. Since defaultTraversalAllDeclarativeModels() isn't working as expected, is there a method/work around for opening a .aadl as a declarative model(as opposed to just reading it as a text string)?

What I'm trying to do is to find all component implementations, check if they meet certain characteristics, modify them based on external files and then unparse back to aadl.

**Comment by lwrage** [comment]
<a href="https://github.com/philip-alldredge"><img src="https://avatars2.githubusercontent.com/u/1376364?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [philip-alldredge](https://github.com/philip-alldredge)**
_Tue Feb 28 17:00:46 2012_

----

Nevermind, I figured it out. The answer is to use OsateResourceUtil.getResource() to open the .aadl file. I thought it only worked on xmi model files.

**Comment by lwrage** [comment]
<a href="https://github.com/reteprelief"><img src="https://avatars1.githubusercontent.com/u/750520?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [reteprelief](https://github.com/reteprelief)**
_Thu Mar  1 03:07:53 2012_

----

Min Young, Philip,

I fixed up the traversals that cover the whole workspace. Instead of traversing the resoruceset they now traverse the file system to find the models to be accessed.
The changes have been pushed to the develop branch.

I also have put together some methods that give you the list of aadl packages, or a list of classifiers (or of a given classifier class, e.g., ProcessorType) by using the EMF index that Xtext maintains for global qualified names.
This works without loading the respective models by giving you an IEObjectDescription for each. That object has the reference (or proxy) to the actual object as well as the EClass of the object.

Look at DoModelStatistics - it has a code illustration of how to use it (in comments).

Still looking at the issue with changes to the model getting updated correctly into text. I have some ideas of what goes wrong.

**Comment by lwrage** [comment]
<a href="https://github.com/philip-alldredge"><img src="https://avatars2.githubusercontent.com/u/1376364?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [philip-alldredge](https://github.com/philip-alldredge)**
_Thu Mar  1 21:23:14 2012_

----

Peter,
Thanks for the updates. 

This may be a case of user error, but I just built the develop branch and I ran across an issue when using defaultTraversalAllDeclarativeModels(). caseComponentImplementation(...) is now called with valid SystemImplementation objects as expected. Unfortunately when I call getAllSubcomponents() on those objects, I get an empty list. Is there anything I need to do to load the complete object. I tried various interactions of resolve and resolveAll without any success. 

I looked at your example for getting classifiers and I was wondering if there is there a way to get an Aadl2LinkingService and getting all the classifiers without needing a model element or resource. In my case I am just trying to find all the classifiers and will edit them conditionally so I do not have a reference to a model element at this time.

**Comment by lwrage** [comment]
<a href="https://github.com/reteprelief"><img src="https://avatars1.githubusercontent.com/u/750520?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [reteprelief](https://github.com/reteprelief)**
_Fri Mar  2 05:54:42 2012_

----

I was able to fix getAadl2LinkingService and getPropertiesLinkingService to work without a parameter.

I added some sample code into DoModelStatistics and the caseComponentImplemetnation in the switch to test out the subcomponent list issue. Works in that code.
pushed to develop branch

**Comment by lwrage** [comment]
<a href="https://github.com/philip-alldredge"><img src="https://avatars2.githubusercontent.com/u/1376364?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [philip-alldredge](https://github.com/philip-alldredge)**
_Fri Mar  2 16:17:24 2012_

----

Thanks. The linking service example worked great. I had to pass in a new resource set in place of the one returned by obj.eResource().getResourceSet(). (Since I don't have resource set to pass in). 

I did some investigation on the defaultTraversalAllDeclarativeModel issue I'm experiencing. For some classifiers, getAllSubcomponents() returns the correct value. On others it returns an empty list. The major difference I have noticed is that the classifiers that work are the ones that do not extend anything. The ones that do not work extend system implementations contained in another project. 

The getAllSubcomponents method works correctly for these same System Implementations when retrieved using the linking service or the resource is loaded directly.

**Comment by lwrage** [comment]
<a href="https://github.com/peterhfeiler"><img src="https://avatars2.githubusercontent.com/u/1461492?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [peterhfeiler](https://github.com/peterhfeiler)**
_Fri Mar  2 16:54:59 2012_

----

Can you send me some sample models to look into this?

Thanks

**Comment by lwrage** [comment]
<a href="https://github.com/philip-alldredge"><img src="https://avatars2.githubusercontent.com/u/1376364?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [philip-alldredge](https://github.com/philip-alldredge)**
_Fri Mar  2 17:16:48 2012_

----

Peter,
I have tried to find the simplest setup that reproduces the issue in my plugin. It requires having two packages. They can both be in the same project. Example below.

Debug.aadl:

```
package Debug
public
    system A
    end A;

system implementation A.impl
subcomponents 
    b1: system;
    end A.impl; 
end Debug;
```

Debug2.aadl:

```
package Debug2
public
    with Debug;

    system AExtended extends Debug::A
    end AExtended;

    system implementation AExtended.impl2 extends Debug::A.impl
    end AExtended.impl2;
end Debug2;
```

**Comment by lwrage** [comment]
<a href="https://github.com/reteprelief"><img src="https://avatars1.githubusercontent.com/u/750520?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [reteprelief](https://github.com/reteprelief)**
_Sat Mar  3 13:13:36 2012_

----

Ok.  I see the error. Will be interesting to trace down. Lutz is using some UML queries in the Meta model to get the subcomponents for each implementation.

**Comment by lwrage** [comment]
<a href="https://github.com/reteprelief"><img src="https://avatars1.githubusercontent.com/u/750520?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [reteprelief](https://github.com/reteprelief)**
_Mon Mar  5 05:02:36 2012_

----

Resolved the issue. Had to do with misunderstanding how XText is managing resourcesets. I ended up creating more than one. This is fixed now. 
If you use the methods that return IEobjectDescriptions from the index allowing you to identifiy packages and classifiers without loading the models, they have moved the the ModelLoadingAdapter from Aadl2LinkingService.

**Comment by lwrage** [comment]
<a href="https://github.com/philip-alldredge"><img src="https://avatars2.githubusercontent.com/u/1376364?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [philip-alldredge](https://github.com/philip-alldredge)**
_Mon Mar 12 21:37:15 2012_

----

Sorry for the delay. defaultTraversalAllDeclarativeModels() is now working as expected. Thanks for the quick fixes!

**Comment by lwrage** [comment]
<a href="https://github.com/philip-alldredge"><img src="https://avatars2.githubusercontent.com/u/1376364?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [philip-alldredge](https://github.com/philip-alldredge)**
_Thu Mar 15 14:48:06 2012_

----

Looks like I've encountered another problem. Relevant portions of the stack trace are below.

```
at org.osate.aadl2.modelsupport.modeltraversal.TraverseWorkspace.getFiles(TraverseWorkspace.java:64)
at org.osate.aadl2.modelsupport.modeltraversal.TraverseWorkspace.getFiles(TraverseWorkspace.java:71)
at org.osate.aadl2.modelsupport.modeltraversal.TraverseWorkspace.getFiles(TraverseWorkspace.java:71)
at org.osate.aadl2.modelsupport.modeltraversal.TraverseWorkspace.getFiles(TraverseWorkspace.java:51)
```

Line 64 in my version of the source is "if (file.getFileExtension().equalsIgnoreCase(WorkspacePlugin.SOURCE_FILE_EXT)".

I believe getFileExtension() returns null if there is a file that does not have one. I haven't been able to find the file that is causing this in my workspace but that seems like the only possible cause.

Update:
This issue started happening sometime after I added the model to a subversion repository. Subversion uses files without extensions in (normally)hidden folders. That may be the cause.

**Comment by lwrage** [comment]
<a href="https://github.com/peterhfeiler"><img src="https://avatars2.githubusercontent.com/u/1461492?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [peterhfeiler](https://github.com/peterhfeiler)**
_Fri Mar 16 04:05:17 2012_

----

Found the problem. getFileExtension was returning null if no extension and an empty string if the file ends with "." (I had assumed it was always an empty string.
I also added filtering out invisible folders, i.e., folders that start with "."
Pushed to develop branch.

**Comment by lwrage** [comment]
<a href="https://github.com/mnam"><img src="https://avatars0.githubusercontent.com/u/1434565?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mnam](https://github.com/mnam)**
_Sat May 12 13:29:56 2012_

----

Hi Peter,

I found an issue and I believe that it is related with this topic again. Above, philip mentioned his problem with getAllSubcomponents() and I am experiencing this as well. I have multiple times done the same procedure and this
always happens and I believe there is a simple fix that is in need.

My tool would try to add a instance of a selected process type to the model. In doing so, 
it would update instance file and the declaritive model where the process is added as a subcomponent. 
I'm using a simple model where all processes are in the top-level system implementation. 
After updating the declaritive model, which is the system implementation in (defined in A_Model.aadl), 
it would unparse and update the A_Model.aadl file.
Up to now it looks like it is working.
After doing this, for testing, I would delete the process subcomponent, that I just added, from the system implementation inside A_Model.aadl from OSATE by typing.
I'll save it. I'll even do a clean of the work space. Delete the old instance model. Remake a new instance model and
load the model into my tool.
When I load the model, I don't see the process that I deleted from the instance model. 
But, when I use
InstanceUtil.getComponentImplementation(systeminstance, 0, null).getAllSubcomponents()
the system implementation that I get is an old one that includes the deleted process subcomponent.
From now on, whatever change I make to the system implementation in the A_Model.aadl file,
it is not applied to the system implementation that I get in code. 
Only way to make it work it right is to rebuild OSATE. I could clean, rebuild the workspace but 
the system implementation that I get would stay the same causing a mismatch in the system instance's
content and the system implementation.

Looks like when I modify the system implementation by code and unparse it, I am breaking something
or it was never suppose to be supported this way.

Thanks.
Sincerely,
Min Young

the A_Model.aadl file

**Comment by lwrage** [comment]
<a href="https://github.com/reteprelief"><img src="https://avatars1.githubusercontent.com/u/750520?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [reteprelief](https://github.com/reteprelief)**
_Sat May 12 13:45:18 2012_

----

Hi Min Young,

It looks like someone is holding on to the old instance model, which still points to the old system implementation. Can you check the resource set the original instance model and resource with the system implementation are in, and then do the same for the new instance model and system implementation resource? 

Also, with the latest sources in the develop branch you will be able to just save the resource - I was able to get the Serializer of Xtext to work.
You can try that instead of the unparse. 
To do the modification of the declarative model, they have a readonly and a modify transaction:
http://koehnlein.blogspot.com/2010/06/semantic-model-access-in-xtext.html

See also the SerializeHandler in org.osate.xtext.aadl2.ui.handlers

Peter

-----Original Message-----

**Comment by lwrage** [comment]
<a href="https://github.com/mnam"><img src="https://avatars0.githubusercontent.com/u/1434565?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mnam](https://github.com/mnam)**
_Sat May 12 14:03:53 2012_

----

Hi Peter,

At first I was suspicious that I may be holding onto the old instance model. But even if I check for the subcomponent
from the system instance by systeminstance.getAllComponentInstances() right before I check its system implementation,
I see that the delete process is not existing in the system instance but the system implementation has the subcomponent.

So, then what I checked is, as soon as my tool starts and get the system instance from 
doAaxlAction(IProgressMonitor monitor, Element obj)
then
final Element systeminstance = obj.getElementRoot();

and when I do 
systeminstance.getAllComponentInstances()
I don't see the subcomponent component instance
but 
InstanceUtil.getComponentImplementation(systeminstance, 0, null).getAllSubcomponents()
 this will show the deleted subcomponent.

So here, practically none of my code is gone through.

I'll try to use the serializer and see what happens.

Thanks!!
Min Young

**Comment by lwrage** [comment]
<a href="https://github.com/reteprelief"><img src="https://avatars1.githubusercontent.com/u/750520?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [reteprelief](https://github.com/reteprelief)**
_Sat May 12 14:48:59 2012_

----

Min Young,

I found a place where Lutz uses a hashtable to access classifiers and prototype bindings more efficiently. That has table is not getting reset.
I'll see if I can fix that.

Peter

-----Original Message-----

**Comment by lwrage** [comment]
<a href="https://github.com/reteprelief"><img src="https://avatars1.githubusercontent.com/u/750520?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [reteprelief](https://github.com/reteprelief)**
_Sat May 12 15:01:04 2012_

----

Hi Min Young,

I fixed the hashtable problem. It was in the InstantiateHandler. It now creates an InstantiateModel object every time it creates an instance object.

You can find the fix in the develop branch.

Peter

-----Original Message-----

**Comment by lwrage** [comment]
<a href="https://github.com/mnam"><img src="https://avatars0.githubusercontent.com/u/1434565?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mnam](https://github.com/mnam)**
_Sat May 12 15:03:43 2012_

----

Thanks for the quick fix Peter,

I'll see how it works.

Min Young

**Comment by lwrage** [comment]
<a href="https://github.com/mnam"><img src="https://avatars0.githubusercontent.com/u/1434565?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mnam](https://github.com/mnam)**
_Sat May 12 16:18:06 2012_

----

Hi Peter,

I'm afraid the change didn't fix this. I'm still seeing the old process as soon as I check after getting the system instance
from doAaxlAction. Not in the system instance but only it its system implementation subcomponent list.
This is even after I do a 
EList<IEObjectDescription> classifierlist = EMFIndexRetrieval.getAllClassifiersInWorkspace();
for (IEObjectDescription cleod : classifierlist){
  Classifier cl = (Classifier) EcoreUtil.resolve(cleod.getEObjectOrProxy(), obj.eResource().getResourceSet());
}

right before checking inside doAaxlAction.

Did more testing and it is really weird.
When I instantiate, I see that a system implementation without the process subcomponent is being set for the created system instance.
When I read the system instance and the move to get the system implementation, it has the deleted process subcomponent while the system instance is correct as explained before.

Min Young

**Comment by lwrage** [comment]
<a href="https://github.com/mnam"><img src="https://avatars0.githubusercontent.com/u/1434565?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mnam](https://github.com/mnam)**
_Sat May 12 16:42:45 2012_

----

Oh also for the same instantiation file that would give me the deleted process subcomponent,
If I close OSATE and rebuild and 
use the same instantiation file without rebuilding, it will no longer show the deleted process subcomponent.

Min Young

**Comment by lwrage** [comment]
<a href="https://github.com/peterhfeiler"><img src="https://avatars2.githubusercontent.com/u/1461492?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [peterhfeiler](https://github.com/peterhfeiler)**
_Sat May 12 20:17:29 2012_

----

Hi Min Young,

Definitely odd.
Are you still unparsing or just saving the file which uses the Xtext 
serializer?
When unparsing the Xtext builder recompiles the file, which may affect 
the references from the instance model into the declarative model.
But why would you get two different system implementations from the same 
instance object? The only thing I can think of is that one access is 
done inside a transaction on the model, while the other is done outside 
- with the transaction completion affecting the reference.

Peter
