### ISSUE TITLE
PermGen space issues with OSATE2 on MacOS X when testing plugins

### ISSUE THREAD

**Issue by lwrage** [lwrage/osate2-core#48]
<a href="https://github.com/yoogx"><img src="https://avatars3.githubusercontent.com/u/1502063?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yoogx](https://github.com/yoogx)**
_Thu Apr 12 15:18:40 2012_
_Originally opened as https://github.com/osate/osate2-core/issues/47_

----

Hi, 

I'm experimenting some errors bound to PermGen space with OSATE2 (march snapshot) on MacOS X
To trigger it, I do the following
- create a plugin for Eclipse, drag in dependencies from OSATE2, e.g. one from one of the analysis plugin from osate repository
- then, do complete the plug-in, and 
- launch it

then create an AADL project, create a file, edit it, then rename it with a ".aadl2" extension to see the crash
the stack trace shows

ENTRY org.eclipse.osgi 4 0 2012-04-12 17:00:53.981
!MESSAGE An error occurred while automatically activating bundle org.osate.xtext.aadl2.ui (367).
!STACK 0
org.osgi.framework.BundleException: Exception in org.osate.xtext.aadl2.ui.MyAadl2Activator.start() of bundle org.osate.xtext.aadl2.ui.
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:734)
[...]
Caused by: java.lang.OutOfMemoryError: PermGen space
    at java.lang.ClassLoader.defineClass1(Native Method)

I increased MaxPermsize to 1024m in osate.ini, so I suspect the issue is elsewhere
It looks like the system enters an infinte loop and eats up the whole memory

Note that I can create AADL projects from OSATE2 directly, but not from the OSATE2 launched from my plug-in dev env

Did I miss something obvious in the process?

**Comment by lwrage** [comment]
<a href="https://github.com/yoogx"><img src="https://avatars3.githubusercontent.com/u/1502063?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yoogx](https://github.com/yoogx)**
_Thu Apr 12 15:24:40 2012_

----

Hum, I spent 4 hours googling for this before, wrote the report, and find a work around 3 minutes after I post this, well ..

when launching the plug-in, one should first set, in the "Run Configurations", the following -XX:MaxPermSize=256m in the Arguments tab, VM arguments box

Closing

**Comment by lwrage** [comment]
<a href="https://github.com/reteprelief"><img src="https://avatars1.githubusercontent.com/u/750520?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [reteprelief](https://github.com/reteprelief)**
_Thu Apr 12 15:36:30 2012_

----

Hi Jerome,

The Eclipse spawned from within the development environment is not pick up the eclipse.ini of the development environment.

You can specify the memory requirements as arguments in the Run or Debug configuration.
See attachment for the dialog box.

Peter

-----Original Message-----
From: Jerome Hugues [mailto:reply@reply.github.com] 
Sent: Thursday, April 12, 2012 11:19 AM
To: Peter Feiler
Subject: [osate2-core] PermGen space issues with OSATE2 on MacOS X when testing plugins (#47)

Hi, 

I'm experimenting some errors bound to PermGen space with OSATE2 (march snapshot) on MacOS X To trigger it, I do the following
- create a plugin for Eclipse, drag in dependencies from OSATE2, e.g. one from one of the analysis plugin from osate repository
- then, do complete the plug-in, and
- launch it

then create an AADL project, create a file, edit it, then rename it with a ".aadl2" extension to see the crash the stack trace shows

ENTRY org.eclipse.osgi 4 0 2012-04-12 17:00:53.981 !MESSAGE An error occurred while automatically activating bundle org.osate.xtext.aadl2.ui (367).
!STACK 0
org.osgi.framework.BundleException: Exception in org.osate.xtext.aadl2.ui.MyAadl2Activator.start() of bundle org.osate.xtext.aadl2.ui.
    at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:734)
[...]
Caused by: java.lang.OutOfMemoryError: PermGen space
    at java.lang.ClassLoader.defineClass1(Native Method)

I increased MaxPermsize to 1024m in osate.ini, so I suspect the issue is elsewhere It looks like the system enters an infinte loop and eats up the whole memory

Note that I can create AADL projects from OSATE2 directly, but not from the OSATE2 launched from my plug-in dev env

Did I miss something obvious in the process?

---

Reply to this email directly or view it on GitHub:
https://github.com/osate/osate2-core/issues/47

**Comment by lwrage** [comment]
<a href="https://github.com/yoogx"><img src="https://avatars3.githubusercontent.com/u/1502063?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yoogx](https://github.com/yoogx)**
_Thu Apr 12 16:47:05 2012_

----

Hi Peter,

Indeed, that did it. I guess we should add a note on the OSATE2 wiki at some point if you agree
